---@class Cgdex3LocalData
Cgdex3LocalData={
sortid = 0,
typeid = 0,
chapterid = 0,
chaptername = "0",
chaptersort = 0,
name = "0",
music = "0",
checkpointid = 0,
time = "0",
chapterpic = "0",
}
---@type Cgdex3LocalData[]
Cgdex3LocalData.tab={
[1] = {sortid = 1,	typeid = 99,	chapterid = 0,	chaptername = "專輯-時間之外",	chaptersort = 1,	name = "Hidden",	music = "6-Thehiddentruth_MP3",	checkpointid = 0,	time = "01,50",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji1",	"0",	"0",	"0",	"许是终幕"},
[2] = {sortid = 2,	typeid = 99,	chapterid = 0,	chaptername = "專輯-時間之外",	chaptersort = 2,	name = "霾",	music = "7-Undertheearth_MP3",	checkpointid = 0,	time = "02,00",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji1",	"0",	"0",	"0",	"领航星"},
[3] = {sortid = 3,	typeid = 99,	chapterid = 0,	chaptername = "專輯-時間之外",	chaptersort = 3,	name = "Ruinofanillusion",	music = "12-ruins_MP3",	checkpointid = 0,	time = "01,56",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji1",	"0",	"0",	"0",	"月面续存"},
[4] = {sortid = 4,	typeid = 99,	chapterid = 0,	chaptername = "專輯-時間之外",	chaptersort = 4,	name = "Abysmalsea",	music = "22-nest_MP3",	checkpointid = 0,	time = "01,52",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji1",	"0",	"0",	"0",	"Overthemoon"},
[5] = {sortid = 5,	typeid = 99,	chapterid = 1,	chaptername = "專輯-蒼穹戰線",	chaptersort = 1,	name = "Warehouse",	music = "3-juesejiemian_MP3",	checkpointid = 100001,	time = "01,52",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2",	"0",	"0",	"0",	"Hidden"},
[6] = {sortid = 6,	typeid = 99,	chapterid = 1,	chaptername = "專輯-蒼穹戰線",	chaptersort = 2,	name = "午茶",	music = "25-Lowtea_MP3",	checkpointid = 100001,	time = "01,52",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2",	"0",	"0",	"0",	"霾"},
[7] = {sortid = 7,	typeid = 99,	chapterid = 1,	chaptername = "專輯-蒼穹戰線",	chaptersort = 3,	name = "許是終幕",	music = "1-Afterallthestories_MP3",	checkpointid = 100008,	time = "02,09",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2",	"0",	"0",	"0",	"Deception"},
[8] = {sortid = 8,	typeid = 99,	chapterid = 1,	chaptername = "專輯-蒼穹戰線",	chaptersort = 4,	name = "Echo",	music = "13-Reverb_MP3",	checkpointid = 100008,	time = "02,15",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2",	"0",	"0",	"0",	"【逆爱】"},
[9] = {sortid = 9,	typeid = 99,	chapterid = 1,	chaptername = "專輯-蒼穹戰線",	chaptersort = 5,	name = "月面續存",	music = "4-Battle-moon_MP3",	checkpointid = 100021,	time = "01,52",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2",	"0",	"0",	"0",	"Piercethehaze"},
[10] = {sortid = 10,	typeid = 99,	chapterid = 1,	chaptername = "專輯-蒼穹戰線",	chaptersort = 6,	name = "間奏二",	music = "20-Battle-Warehouse2_MP3",	checkpointid = 100021,	time = "01,39",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2",	"0",	"0",	"0",	"Melpomene"},
[11] = {sortid = 11,	typeid = 99,	chapterid = 1,	chaptername = "專輯-蒼穹戰線",	chaptersort = 7,	name = "Overthemoon",	music = "5-overthemoon_MP3",	checkpointid = 100021,	time = "02,00",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2",	"0",	"0",	"0",	"残响其一"},
[12] = {sortid = 12,	typeid = 99,	chapterid = 1,	chaptername = "專輯-蒼穹戰線",	chaptersort = 8,	name = "【逆愛】",	music = "9-Battle-niai",	checkpointid = 100031,	time = "02,02",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2",	"0",	"0",	"0",	"Ruinofanillusion"},
[13] = {sortid = 13,	typeid = 99,	chapterid = 1,	chaptername = "專輯-蒼穹戰線",	chaptersort = 9,	name = "Deception",	music = "8-Deception_MP3",	checkpointid = 100033,	time = "02,00",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2",	"0",	"0",	"0",	"Heroicepic"},
[14] = {sortid = 14,	typeid = 99,	chapterid = 1,	chaptername = "專輯-蒼穹戰線",	chaptersort = 10,	name = "殘響其一",	music = "0-pv_MP3",	checkpointid = 100039,	time = "02,20",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji2",	"0",	"0",	"0",	"Unstoppable"},
[15] = {sortid = 15,	typeid = 99,	chapterid = 2,	chaptername = "專輯-濃霧港灣",	chaptersort = 1,	name = "回收策略",	music = "Battle-ziyuan_MP3",	checkpointid = 100101,	time = "02,08",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji3",	"0",	"0",	"0",	"间奏二"},
[16] = {sortid = 16,	typeid = 99,	chapterid = 2,	chaptername = "專輯-濃霧港灣",	chaptersort = 2,	name = "領航星",	music = "2-zhujiemian_MP3",	checkpointid = 100103,	time = "02,26",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji3",	"0",	"0",	"0",	"间奏三"},
[17] = {sortid = 17,	typeid = 99,	chapterid = 2,	chaptername = "專輯-濃霧港灣",	chaptersort = 3,	name = "間奏三",	music = "21-Battle-Warehouse3_MP3",	checkpointid = 100104,	time = "01,38",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji3",	"0",	"0",	"0",	"Abysmalsea"},
[18] = {sortid = 18,	typeid = 99,	chapterid = 2,	chaptername = "專輯-濃霧港灣",	chaptersort = 4,	name = "間奏一",	music = "19-Battle-Warehouse_MP3",	checkpointid = 100128,	time = "01,53",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji3",	"0",	"0",	"0",	"微乎其微的抗争"},
[19] = {sortid = 19,	typeid = 99,	chapterid = 2,	chaptername = "專輯-濃霧港灣",	chaptersort = 5,	name = "Heroicepic",	music = "15-Battle-Sobek_MP3",	checkpointid = 100134,	time = "01,53",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji3",	"0",	"0",	"0",	"Distantblue"},
[20] = {sortid = 20,	typeid = 99,	chapterid = 3,	chaptername = "專輯-海市蜃樓",	chaptersort = 1,	name = "Twerp",	music = "26-twerp_MP3",	checkpointid = 100200,	time = "01,43",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji4",	"0",	"0",	"0",	"午茶"},
[21] = {sortid = 21,	typeid = 99,	chapterid = 3,	chaptername = "專輯-海市蜃樓",	chaptersort = 2,	name = "Melpomene",	music = "11-Mnemosyne_MP3",	checkpointid = 100208,	time = "02,05",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji4",	"0",	"0",	"0",	"Warehouse"},
[22] = {sortid = 22,	typeid = 99,	chapterid = 3,	chaptername = "專輯-海市蜃樓",	chaptersort = 3,	name = "Piercethehaze",	music = "10-Piercethehaze_MP3",	checkpointid = 100230,	time = "01,54",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji4",	"0",	"0",	"0",	"Echo"},
[23] = {sortid = 23,	typeid = 99,	chapterid = 3,	chaptername = "專輯-海市蜃樓",	chaptersort = 4,	name = "Unstoppable",	music = "16-Battle-Jormungand_MP3",	checkpointid = 100236,	time = "01,53",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji4",	"0",	"0",	"0",	"Twerp"},
[24] = {sortid = 24,	typeid = 99,	chapterid = 3,	chaptername = "專輯-海市蜃樓",	chaptersort = 5,	name = "微乎其微的抗爭",	music = "23-light_MP3",	checkpointid = 100237,	time = "01,32",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji4",	"0",	"0",	"0",	"回收策略"},
[25] = {sortid = 25,	typeid = 99,	chapterid = 4,	chaptername = "專輯-心之所向",	chaptersort = 1,	name = "Distantblue",	music = "24-Distantbluesea_MP3",	checkpointid = 100332,	time = "01,57",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji5",	"0",	"0",	"0",	"间奏一"},
[26] = {sortid = 26,	typeid = 99,	chapterid = 4,	chaptername = "專輯-心之所向",	chaptersort = 2,	name = "安潔莉卡",	music = "17-Battle-jidu_MP3",	checkpointid = 100330,	time = "01,55",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji5",	"0",	"0",	"0",	"0"},
[27] = {sortid = 27,	typeid = 99,	chapterid = 100,	chaptername = "專輯-午後與糖",	chaptersort = 1,	name = "靜夜",	music = "28-Silent_night",	checkpointid = 100039,	time = "01,02",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji0",	"0",	"0",	"0",	"静夜"},
[28] = {sortid = 28,	typeid = 99,	chapterid = 100,	chaptername = "專輯-午後與糖",	chaptersort = 2,	name = "CoffeeHouse",	music = "27-Coffee_House",	checkpointid = 100101,	time = "01,09",	chapterpic = "ArtGallery/MusicPic/Img_Zhuanji0",	"0",	"0",	"0",	"CoffeeHouse"},
}
return Cgdex3LocalData