SamplevoiceLocalData={}
SamplevoiceLocalData.tab={
[1] = {1,	"领航",	1,	1,	"sample_linghang_1",	"touxiang_linghang"},
[2] = {2,	"领航",	1,	1,	"sample_linghang_2",	"touxiang_linghang"},
[3] = {3,	"领航",	1,	1,	"sample_linghang_3",	"touxiang_linghang"},
[4] = {4,	"吉雅",	2,	1,	"sample_jiya_1",	"touxiang_jiya"},
[5] = {5,	"吉雅",	2,	1,	"sample_jiya_2",	"touxiang_jiya"},
[6] = {6,	"吉雅",	2,	1,	"sample_jiya_3",	"touxiang_jiya"},
[7] = {7,	"史蒂芬妮",	3,	1,	"sample_shidifenni_1",	"touxiang_shidifenni"},
[8] = {8,	"史蒂芬妮",	3,	1,	"sample_shidifenni_2",	"touxiang_shidifenni"},
[9] = {9,	"史蒂芬妮",	3,	1,	"sample_shidifenni_3",	"touxiang_shidifenni"},
[10] = {10,	"查丽莎",	4,	1,	"sample_chalisha_1",	"touxiang_chalisha"},
[11] = {11,	"查丽莎",	4,	1,	"sample_chalisha_2",	"touxiang_chalisha"},
[12] = {12,	"查丽莎",	4,	1,	"sample_chalisha_3",	"touxiang_chalisha"},
[13] = {13,	"弗兰卡",	5,	1,	"sample_fulanka_1",	"touxiang_fulanka"},
[14] = {14,	"弗兰卡",	5,	1,	"sample_fulanka_2",	"touxiang_fulanka"},
[15] = {15,	"弗兰卡",	5,	1,	"sample_fulanka_3",	"touxiang_fulanka"},
[16] = {16,	"朱利乌斯",	6,	1,	"sample_zhuliwusi_1",	"touxiang_zhuliwusi"},
[17] = {17,	"朱利乌斯",	6,	1,	"sample_zhuliwusi_2",	"touxiang_zhuliwusi"},
[18] = {18,	"朱利乌斯",	6,	1,	"sample_zhuliwusi_3",	"touxiang_zhuliwusi"},
[19] = {19,	"其他",	7,	1,	"sample_other_1",	"touxiang_qita"},
[20] = {20,	"其他",	7,	1,	"sample_other_2",	"touxiang_qita"},
[21] = {21,	"其他",	7,	1,	"sample_other_3",	"touxiang_qita"},
}
return SamplevoiceLocalData