---@class SummermazetalkLocalData
SummermazetalkLocalData={
id = 0,
groupid = 0,
icon = "0",
name = "0",
text = "0",
locat = 0,
sound = "0",
spine = "0",
}
---@type SummermazetalkLocalData[]
SummermazetalkLocalData.tab={
[1] = {id = 1,	groupid = 1001,	icon = "xueshengA",	name = "學生A",	text = "哦——是男生。",	locat = 2,	sound = "0",	spine = "0"},
[2] = {id = 2,	groupid = 1001,	icon = "xueshengB",	name = "學生B",	text = "哦哦——是男生。",	locat = 1,	sound = "0",	spine = "0"},
[3] = {id = 3,	groupid = 1001,	icon = "linghang",	name = "領航",	text = "（好像有很多人在看我。）",	locat = 2,	sound = "0",	spine = "0"},
[4] = {id = 4,	groupid = 1002,	icon = "xueshengB",	name = "學生B",	text = "會長就在前面等你。",	locat = 2,	sound = "0",	spine = "0"},
[5] = {id = 5,	groupid = 1002,	icon = "Sikadi",	name = "斯卡蒂",	text = "咦！果然有獸人！吾剛剛果然沒有看錯！\n好漂亮哦，吾能摸摸你的手嗎！",	locat = 1,	sound = "0",	spine = "0"},
[6] = {id = 6,	groupid = 1002,	icon = "xueshengB",	name = "學生B",	text = "……你只是想摸我手上的肉球吧？",	locat = 2,	sound = "0",	spine = "0"},
[7] = {id = 7,	groupid = 1003,	icon = "xueshengA",	name = "學生A",	text = "深呼一口氣，堅持住吧。",	locat = 2,	sound = "0",	spine = "0"},
[8] = {id = 8,	groupid = 1003,	icon = "xueshengA",	name = "學生A",	text = "路就在前邊。",	locat = 2,	sound = "0",	spine = "0"},
[9] = {id = 9,	groupid = 1004,	icon = "huizhang",	name = "會長",	text = "哦，了不得！這裡是特殊探索關卡。",	locat = 2,	sound = "0",	spine = "0"},
[10] = {id = 10,	groupid = 1004,	icon = "huizhang",	name = "會長",	text = "斯卡蒂，你就閉上眼睛在黑暗中探索吧。",	locat = 2,	sound = "0",	spine = "0"},
[11] = {id = 11,	groupid = 1004,	icon = "Sikadi",	name = "斯卡蒂",	text = "等一下——本來就這麼黑暗閉上眼睛還怎麼走路啊！",	locat = 1,	sound = "0",	spine = "0"},
[12] = {id = 12,	groupid = 1004,	icon = "huizhang",	name = "會長",	text = "“心眼”，你會的吧？用心看清周圍的事物。",	locat = 2,	sound = "0",	spine = "0"},
[13] = {id = 13,	groupid = 1004,	icon = "huizhang",	name = "會長",	text = "在特殊探索關卡中存在陷阱，陷阱外觀與普通格相同請小心前進。",	locat = 2,	sound = "0",	spine = "0"},
[14] = {id = 14,	groupid = 1004,	icon = "Sikadi",	name = "斯卡蒂",	text = "還有陷阱！為什麼要在自己的大本營裡設置陷阱——",	locat = 1,	sound = "0",	spine = "0"},
[15] = {id = 15,	groupid = 1004,	icon = "huizhang",	name = "會長",	text = "這是從一開始就存在的啦，踩中了陷阱會回退到上一格。",	locat = 2,	sound = "0",	spine = "0"},
[16] = {id = 16,	groupid = 1004,	icon = "huizhang",	name = "會長",	text = "我也不知道設置這些陷阱的人究竟是有什麼特殊癖好。",	locat = 2,	sound = "0",	spine = "0"},
[17] = {id = 17,	groupid = 1004,	icon = "Sikadi",	name = "斯卡蒂",	text = "唔，吾明白了，總之前進就對了吧？",	locat = 1,	sound = "0",	spine = "0"},
[18] = {id = 18,	groupid = 1004,	icon = "linghang",	name = "領航",	text = "你真的明白了嗎……",	locat = 2,	sound = "0",	spine = "0"},
[19] = {id = 19,	groupid = 1005,	icon = "xueshengB",	name = "學生B",	text = "你們要去許願湖嗎？",	locat = 2,	sound = "0",	spine = "0"},
[20] = {id = 20,	groupid = 1005,	icon = "xueshengB",	name = "學生B",	text = "嗯哼~讓我看看你們會許什麼樣的願望呢~",	locat = 2,	sound = "0",	spine = "0"},
[21] = {id = 21,	groupid = 1005,	icon = "xueshengB",	name = "學生B",	text = "好期待哦！",	locat = 2,	sound = "0",	spine = "0"},
[22] = {id = 22,	groupid = 1006,	icon = "linghang",	name = "領航",	text = "原罪？！不是說上之島已經沒有原罪了——",	locat = 2,	sound = "0",	spine = "0"},
[23] = {id = 23,	groupid = 1006,	icon = "sikadi_s",	name = "斯卡蒂",	text = "是試煉吧！",	locat = 1,	sound = "0",	spine = "0"},
[24] = {id = 24,	groupid = 1006,	icon = "sikadi_s",	name = "斯卡蒂",	text = "看招！",	locat = 1,	sound = "0",	spine = "0"},
[25] = {id = 25,	groupid = 1007,	icon = "jieshuxi",	name = "結束希",	text = "這個是……寶箱……？",	locat = 2,	sound = "0",	spine = "0"},
[26] = {id = 26,	groupid = 1007,	icon = "duoluoxi",	name = "桃樂西",	text = "誒——",	locat = 1,	sound = "0",	spine = "0"},
[27] = {id = 27,	groupid = 1007,	icon = "duoluoxi",	name = "桃樂西",	text = "小心是寶箱怪哦。",	locat = 1,	sound = "0",	spine = "0"},
[28] = {id = 28,	groupid = 1007,	icon = "linghang",	name = "領航",	text = "這座島上是不會有寶箱怪這種生物的……",	locat = 2,	sound = "0",	spine = "0"},
[29] = {id = 29,	groupid = 1008,	icon = "qishiA",	name = "騎士A",	text = "誒？！男生？",	locat = 2,	sound = "0",	spine = "0"},
[30] = {id = 30,	groupid = 1008,	icon = "qishiB",	name = "騎士B",	text = "不會吧……",	locat = 1,	sound = "0",	spine = "0"},
[31] = {id = 31,	groupid = 1008,	icon = "qishiA",	name = "騎士A",	text = "不得了，不得了……我要去和大家講！",	locat = 2,	sound = "0",	spine = "0"},
[32] = {id = 32,	groupid = 1009,	icon = "qishiA",	name = "騎士A",	text = "你好，可以和你合拍一張照嗎？",	locat = 2,	sound = "0",	spine = "0"},
[33] = {id = 33,	groupid = 1009,	icon = "linghang",	name = "領航",	text = "啊……好。",	locat = 1,	sound = "0",	spine = "0"},
[34] = {id = 34,	groupid = 1009,	icon = "linghang",	name = "領航",	text = "（……被當成珍稀動物看待了。）",	locat = 1,	sound = "0",	spine = "0"},
[35] = {id = 35,	groupid = 1010,	icon = "huwan",	name = "狐丸",	text = "某處的機關鬆動了。",	locat = 2,	sound = "0",	spine = "0"},
[36] = {id = 36,	groupid = 1011,	icon = "qishiB",	name = "騎士B",	text = "前往boss的路障已解鎖。",	locat = 2,	sound = "0",	spine = "0"},
[37] = {id = 37,	groupid = 1011,	icon = "jieshuxi",	name = "結束希",	text = "哦！",	locat = 1,	sound = "0",	spine = "0"},
[38] = {id = 38,	groupid = 1011,	icon = "jieshuxi",	name = "結束希",	text = "這個就是那個吧！真人NPC扮演！第一次見！",	locat = 1,	sound = "0",	spine = "0"},
[39] = {id = 39,	groupid = 1011,	icon = "qishiB",	name = "騎士B",	text = "……前往boss的路障已解鎖。",	locat = 2,	sound = "0",	spine = "0"},
[40] = {id = 40,	groupid = 1011,	icon = "linghang",	name = "領航",	text = "（一臉不情願的樣子啊……）",	locat = 1,	sound = "0",	spine = "0"},
[41] = {id = 41,	groupid = 1012,	icon = "qishiA",	name = "騎士A",	text = "尋找到藏在地圖上的狐丸就可以開啟寶箱啦！",	locat = 2,	sound = "0",	spine = "0"},
[42] = {id = 42,	groupid = 1013,	icon = "Iing_s",	name = "鈴",	text = "斯卡蒂……我很抱歉。",	locat = 2,	sound = "0",	spine = "0"},
[43] = {id = 43,	groupid = 1013,	icon = "sikadi_s",	name = "斯卡蒂",	text = "嗯……鈴，謝謝你和吾講這些。",	locat = 1,	sound = "0",	spine = "0"},
[44] = {id = 44,	groupid = 1013,	icon = "sikadi_s",	name = "斯卡蒂",	text = "但是，我覺得，這種還是由吾自己決定比較好。",	locat = 1,	sound = "0",	spine = "0"},
[45] = {id = 45,	groupid = 1014,	icon = "xueshengA",	name = "學生A",	text = "會長永遠是會長。",	locat = 2,	sound = "0",	spine = "0"},
[46] = {id = 46,	groupid = 1014,	icon = "xueshengA",	name = "學生A",	text = "所以我們會陪伴她到最後的。",	locat = 2,	sound = "0",	spine = "0"},
[47] = {id = 47,	groupid = 1015,	icon = "qishiA",	name = "騎士A",	text = "真不可思議……",	locat = 2,	sound = "0",	spine = "0"},
[48] = {id = 48,	groupid = 1015,	icon = "qishiA",	name = "騎士A",	text = "王女竟然和我們打過招呼之後才離開。",	locat = 2,	sound = "0",	spine = "0"},
[49] = {id = 49,	groupid = 1015,	icon = "qishiA",	name = "騎士A",	text = "我害怕了……",	locat = 2,	sound = "0",	spine = "0"},
[50] = {id = 50,	groupid = 1016,	icon = "xueshengB",	name = "學生B",	text = "就在這裡坐下吧。",	locat = 2,	sound = "0",	spine = "0"},
[51] = {id = 51,	groupid = 1016,	icon = "qishiB",	name = "騎士B",	text = "嗯，開始吧，我們的計畫。",	locat = 1,	sound = "0",	spine = "0"},
[52] = {id = 52,	groupid = 1017,	icon = "Iing_s",	name = "鈴",	text = "咦咦？！他們在幹什麼！",	locat = 2,	sound = "0",	spine = "0"},
[53] = {id = 53,	groupid = 1017,	icon = "duoluoxi",	name = "桃樂西",	text = "他們果然抱在一起了……",	locat = 1,	sound = "0",	spine = "0"},
[54] = {id = 54,	groupid = 1017,	icon = "duoluoxi",	name = "桃樂西",	text = "我在預言中看見的果然看錯……",	locat = 1,	sound = "0",	spine = "0"},
[55] = {id = 55,	groupid = 1017,	icon = "duoluoxi",	name = "桃樂西",	text = "那麼這次的結局，就是正確的選擇。",	locat = 1,	sound = "0",	spine = "0"},
[56] = {id = 56,	groupid = 1018,	icon = "jieshuxi",	name = "結束希",	text = "啊呀，那邊有一個看起來很奇怪的寶箱。",	locat = 2,	sound = "0",	spine = "0"},
[57] = {id = 57,	groupid = 1018,	icon = "linghang",	name = "領航",	text = "我已經受夠寶箱怪了……",	locat = 1,	sound = "0",	spine = "0"},
[58] = {id = 58,	groupid = 1018,	icon = "sikadi_s",	name = "斯卡蒂",	text = "但是有一塊奇怪的石頭擋著！",	locat = 2,	sound = "0",	spine = "0"},
[59] = {id = 59,	groupid = 1018,	icon = "linghang",	name = "領航",	text = "我已經受夠石頭了……",	locat = 1,	sound = "0",	spine = "0"},
[60] = {id = 60,	groupid = 1018,	icon = "duoluoxi",	name = "桃樂西",	text = "封印的力量比以往的更強盛……",	locat = 2,	sound = "0",	spine = "0"},
[61] = {id = 61,	groupid = 1018,	icon = "duoluoxi",	name = "桃樂西",	text = "恐怕要找到兩處機關才能擊碎。",	locat = 2,	sound = "0",	spine = "0"},
[62] = {id = 62,	groupid = 1018,	icon = "jieshuxi",	name = "結束希",	text = "出發吧！",	locat = 1,	sound = "0",	spine = "0"},
[63] = {id = 63,	groupid = 1018,	icon = "linghang",	name = "領航",	text = "我已經受夠繞路了……",	locat = 2,	sound = "0",	spine = "0"},
[64] = {id = 64,	groupid = 1018,	icon = "jieshuxi",	name = "結束希",	text = "如果需要我的話，就用青草味的蛋黃榴槤芝士蛋糕呼喚我吧。",	locat = 2,	sound = "0",	spine = "0"},
[65] = {id = 65,	groupid = 1019,	icon = "huizhang_b",	name = "會長",	text = "嘖，它的行動更暴躁了。",	locat = 2,	sound = "0",	spine = "0"},
[66] = {id = 66,	groupid = 1019,	icon = "huizhang_b",	name = "會長",	text = "那邊還沒有好嗎？",	locat = 2,	sound = "0",	spine = "0"},
[67] = {id = 67,	groupid = 1020,	icon = "wangnv",	name = "王女",	text = "已經很近了……",	locat = 2,	sound = "0",	spine = "0"},
[68] = {id = 68,	groupid = 1020,	icon = "wangnv",	name = "王女",	text = "如果實在沒辦法，我就……",	locat = 2,	sound = "0",	spine = "0"},
[69] = {id = 69,	groupid = 1021,	icon = "xiangzi",	name = "響子",	text = "“請你們親眼見證吧。”",	locat = 2,	sound = "0",	spine = "0"},
[70] = {id = 70,	groupid = 1021,	icon = "xiangzi",	name = "響子",	text = "噗噗……",	locat = 2,	sound = "0",	spine = "0"},
[71] = {id = 71,	groupid = 1021,	icon = "linghang",	name = "領航",	text = "原來你一直在旁邊嗎？！",	locat = 1,	sound = "0",	spine = "0"},
[72] = {id = 72,	groupid = 1021,	icon = "Sikadi",	name = "斯卡蒂",	text = "呀！呀啊啊啊啊啊啊——",	locat = 1,	sound = "0",	spine = "0"},
[73] = {id = 73,	groupid = 1021,	icon = "xiangzi",	name = "響子",	text = "別害羞嘛。",	locat = 2,	sound = "0",	spine = "0"},
[74] = {id = 74,	groupid = 1021,	icon = "xiangzi",	name = "響子",	text = "快去吧，許願湖的路在那裡，祝你們一路順風。",	locat = 2,	sound = "0",	spine = "0"},
[75] = {id = 75,	groupid = 1022,	icon = "linghang",	name = "領航",	text = "這裡被堵住了……先去其它地方看看吧。",	locat = 2,	sound = "0",	spine = "0"},
[76] = {id = 76,	groupid = 1023,	icon = "linghang",	name = "領航",	text = "先去其它地方看看吧……這裡被堵住了。",	locat = 2,	sound = "0",	spine = "0"},
}
return SummermazetalkLocalData